add_rules("mode.release")
--set_toolchains("mingw")
--set_encodings("utf-8")
-- 设置使用动态运行时库 (MD)
set_toolchains("msvc")
--set_toolchains("msvc", {runtime = "MD"})
--set_toolchains("msvc", {vs_toolset = "14.43.34604"})
set_languages("c++17")
add_requires("spdlog")

add_linkdirs("C:/Users/wuxianggujun/CodeSpace/CMakeProjects/TinaToolBox/dependencies/pdfium-win-x64/lib")
add_linkdirs("C:/Users/wuxianggujun/CodeSpace/CMakeProjects/TinaToolBox/dependencies/pdfium-win-x64/bin")
--add_requires("cmake::PDFium", {alias = "PDFium", configs = {envs = {CMAKE_PREFIX_PATH = "C:/Users/wuxianggujun/CodeSpace/CMakeProjects/TinaToolBox/dependencies/pdfium-win-x64"}}})

target("TinaToolBox")
    add_rules("qt.application")
    add_frameworks("QtWidgets","QtSql","QtNetwork", "QtGui","QtQuick")
    add_includedirs("include")
    add_includedirs("dependencies/pdfium-win-x64/include")
    add_headerfiles("include/*.hpp")
    add_files("src/*.cpp")
    add_packages("spdlog","PDFium")
    add_links("pdfium") 
    --add_cxflags("/utf-8")
